### ISSUE TITLE
API 사용 관련

### ISSUE THREAD

**Issue by lani009** [pengm2ng/AJOU_DATABASE_JMT#2]
# 지출 집행 API
## 설명
[경기도 지출집행 현황](https://data.gg.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=6OCWFQQYK6U2PD0FKSMV27162290&infSeq=2&order=&loc=&searchWord=%EC%97%85%EB%AC%B4%EC%B6%94%EC%A7%84)

## 통계목 코드
[통계목 코드](https://www.dobong.go.kr/wdb_dev/expenditure/PopUpEhojoMokList.asp)

**Comment by pengm2ng** [comment]
# 지도 API
## 설명
경기도 음식점 지도 상 위치
